### PR TITLE
[FormBundle] Add length validation to form fields

### PR DESCRIPTION
**Pull request by dannyvw**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | comma separated list of tickets fixed by the PR

The max length in the database is 255. Without validation you get an database error.

### CODE REVIEW

**Review by ProfessorKuma — CHANGES_REQUESTED** [review]
Hi @, your PR needs some changes
* It seems that you should have submitted to the latest minor branch.
* This PR seems to need a milestone of a patch release.

**Review by acrobat — APPROVED** [review]

**Comment by acrobat** [comment]
@dannyvw thanks for the PR! Can you just rebase it againt the 5.6 branch? Thanks.

**Review by ProfessorKuma — APPROVED** [review]
Hi @, your PR passed all our requirements.

Thank you for contributing!

**Comment by dannyvw** [comment]
@acrobat Done!

**Comment by acrobat** [comment]
Thanks @dannyvw!

**Pull request merged**
