### PR TITLE
[LeadGenerationBundle] fixed doc, getAdminType should be string

### PR DESCRIPTION
**Pull request by virtualize**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  |no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | 

just a minor doc update

### CODE REVIEW

**Review by ProfessorKuma — APPROVED** [review]
Hi @, your PR passed all our requirements.

Thank you for contributing!

**Comment by acrobat** [comment]
Thanks for the PR @virtualize, can you change the other `return new XXX();` usages in this doc page? Thanks!

**Comment by virtualize** [comment]
@acrobat Done.

**Review by acrobat — APPROVED** [review]

**Comment by acrobat** [comment]
Thanks @virtualize!

**Pull request merged**
