### PR TITLE
[AdminBundle] Remember editor content when dragging and dropping

### PR DESCRIPTION
**Pull request by waaghals**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | N/A

Fixes a bug where the content of the WYSIWYG editor is not saved when dragging and dropping.

### CODE REVIEW

**Comment by acrobat** [comment]
@waaghals can you rebase this PR on the 5.4 branch? Thanks!

**Comment by acrobat** [comment]
Ping @waaghals, can you rebase this PR on the 5.4 branch? Thanks!

**Comment by waaghals** [comment]
Sorry for the late reply. Should be fixed now!
Something went wrong during rebasing. So I cherry-pick the commit again on top of the 5.4 branch.

Can you confirm the changes are from the correct branch now?

**Comment by acrobat** [comment]
@waaghals yes, this looks good! Thanks!

**Pull request merged**
