### PR TITLE
[AdminBundle] fixed undefined index client_id

### PR DESCRIPTION
**Pull request by slaci**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | #1124 

Parameters remain defined even in disabled status, because a service requires them...

### CODE REVIEW

**Comment by Numkil** [comment]
+1 Smart fix, could you edit the cookbook section about google signin in the documentation to reflect the changes you made? Thanks!

**Comment by fchris82** [comment]
+1

**Comment by slaci** [comment]
Well, this only fixes the bug fast, but isn't smart. If you write `enabled: false` then it fails, because the isRequired() on the children (if you omit this then works fine ofc). The only way to fix this to check the requirements in the extension and throw exception (there is some configurationexception or something i think that fits here). when neccessary afaik.

**Comment by slaci** [comment]
I updated the PR with the mentioned check. Now `enabled: false` works alone too.

About the [cookbook](https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/master/docs/05-13-enabling-google-auth-login.md), i don't think its need any update cause this. All the same after this, just no fatal error by default. The only change is: now `google_signin: false` means the same as `enabled: false` cause the canBeEnabled() stuff, but thats very minor.

**Comment by fchris82** [comment]
@slaci Maybe there is a better solution. Use the `beforeNormalization()` function, then throw exception if it is enabled but doesn't set the required values: http://php-and-symfony.matthiasnoback.nl/2011/11/symfony2-define-your-bundles-configuration-values-using-the-treebuilder/
See the `Before normalization - then what?` block.

**Comment by slaci** [comment]
Ok now its 100% done! Refactored to 1 commit.

**Pull request merged**
