### PR TITLE
[WIP][NodeBundle] Disallow trailing slash in slug router

### PR DESCRIPTION
**Pull request by waaghals**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | N/A

Changed the regex to not allow trailing slashes. This way, trailing slashes will fallback to the symfony router, which (when correctly configured) will redirect the page without the slash.

This fixes a bug where the main page under a locale path (example.com/en) has duplicate content because both the trailing slash and non trailing slash return the same content.

### CODE REVIEW

**Review by ProfessorKuma — CHANGES_REQUESTED** [review]
Hi @, your PR needs some changes
* It seems that you should have submitted to the latest minor branch.
* This PR seems to need a milestone of a patch release.
* your PR title should look like `[SomeBundle] Fixed some code`

**Comment by acrobat** [comment]
@waaghals I think we then also need to make sure that when saving a slug we remove any trailing slashes, because currently that might be possible

**Review by ProfessorKuma — CHANGES_REQUESTED** [review]
Hi @, your PR needs some changes
* This PR seems to need a milestone of a minor release.

**Review by ProfessorKuma — APPROVED** [review]
Hi @, your PR passed all our requirements.

Thank you for contributing!

**Comment by waaghals** [comment]
I realized this won't work when the slug is left empty when saving a Node. I'll have to figure out a different solution

**Pull request closed without merging**
