### PR TITLE
[AdminBundle] Deprecate Form Types in favour of Symfony namespacing c…

### PR DESCRIPTION
**Pull request by delboy1978uk**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | yes
| Fixed tickets | #1722

### CODE REVIEW

**Comment by delboy1978uk** [comment]
All form types have now been deprecated, we can start using the new ones now!

**Comment by delboy1978uk** [comment]
Commits have been squashed :-)

**Comment by sandergo90** [comment]
@delboy1978uk did you also change the generators ? Because they will need to use the new form type.

**Comment by delboy1978uk** [comment]
No, I just created the new form types. The old ones are still there, so nothing has broken. 

The difference is the old classes now extend the new ones, all the methods moved into the new ones, and @deprecated tags have been added to the old ones. So code will run normally, and PHPStorm will score through any usage of the old ones, and it's as simple as adjusting the namespace to upgrade.

I guess I could do a site wide search for uses within the bundles and replace them too then?

**Comment by sandergo90** [comment]
@delboy1978uk I understand that you deprecated the old ones. But you now created the new ones, so the generators will need to use the new ones. Otherwise new projects will still use the deprecated forms. So maybe site wide search will do the trick ;-)

**Comment by acrobat** [comment]
on second thought I'm 👎on this change as it is deprecating for the sake of deprecating and changing our code (which is perfectly fine) to keep a tool happy. It will also generate more work for our users to upgrade with "real" benefits.

**Comment by Devolicious** [comment]
I'm with @acrobat on this. We just need to fix that particular rule in sensiolabs insight I think. So for now I'm gonna close this PR. Sorry @delboy1978uk.

**Pull request closed without merging**
