### PR TITLE
[AllBundles] Require individual symfony packages

### PR DESCRIPTION
**Pull request by acrobat**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | 

This PR needs to be merged after #2060 (rebased needed). Diff is best viewed as [a0d861a...f04f0fa](https://github.com/Kunstmaan/KunstmaanBundlesCMS/pull/2061/files/f04f0fa5526f248d5b6b955553cb7707271bb1f4). **This PR is also best to be merged with a merge commit (not a squash merge)**, to preserve the specific commits for better history.

Don't require the `symfony/symfony` package as this is not recommended anymore. Instead only require the specific packages used by the cms.

### CODE REVIEW

**Comment by Numkil** [comment]
@acrobat #2060 has been merged now.

**Comment by acrobat** [comment]
@Numkil Rebased!

**Comment by Numkil** [comment]
Please check the following things.
Framework bundle from symfony is probably required?
Symfony monolog bundle has to be added to the standard edition requirements, since it is no longer available from the base bundles.
Adjust Upgrade markdown file to mention potential breaking if relying on the symfony monolog bundle

**Comment by acrobat** [comment]
@Numkil I've added the `symfony/framework-bundle` and `symfony/twig-bundle` packages. As we reference them in our code.

A new upgrade doc was added for the removal of the unused monolog package. And I've created PR in the standard-edition to add the monolog package there. See Kunstmaan/KunstmaanBundlesStandardEdition#268

**Comment by acrobat** [comment]
I've tested this PR with a sf3.4 and kunstmaanbundle 5.1 installation of the standard edition and with a sf4 website skeleton project. Everything seems to work as expected

**Pull request merged**
