### PR TITLE
[AdminBundle] Fix icons in url chooser

### PR DESCRIPTION
**Pull request by dannyvw**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | #2734 

This was added in https://github.com/Kunstmaan/KunstmaanBundlesCMS/commit/c5c43667d97c2f5533b9641be9f4c2c9d2d04711#diff-b4e32d0791eb3212840817f5fa019f37 and removed in https://github.com/Kunstmaan/KunstmaanBundlesCMS/commit/8aa8daf58744440332ac004ddfed991493186b3e#diff-b4e32d0791eb3212840817f5fa019f37

### CODE REVIEW

**Review by ProfessorKuma — CHANGES_REQUESTED** [review]
Hi @, your PR needs some changes
* It seems that you should have submitted to the latest minor branch.
* This PR seems to need a milestone of a patch release.

**Comment by acrobat** [comment]
@dannyvw Can you rebase against the 5.5 branch? Thanks!

**Review by acrobat — APPROVED** [review]

**Review by ProfessorKuma — APPROVED** [review]
Hi @, your PR passed all our requirements.

Thank you for contributing!

**Comment by dannyvw** [comment]
@acrobat Done

**Pull request merged**
