### PR TITLE
[AdminBundle] Updated translations

### PR DESCRIPTION
**Pull request by dannyvw**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets |

### CODE REVIEW

**Comment by jockri** [comment]
Why is this a bug? We prefer key based translation strings.

**Comment by dannyvw** [comment]
It renders "form.cancel" instead of "Cancel"

**Comment by jockri** [comment]
Then there is a translations missage missing. Can you check this?

**Comment by dannyvw** [comment]
The AdminBundle has as parent FOSUserBundle and there is no translation for "form.cancel"

**Comment by jockri** [comment]
You can pass an other domain in the template so it uses the messages domain.

**Comment by dannyvw** [comment]
True, but KunstmaanAdminBundle is not a valid domain, so which domain you want to pass?

**Comment by jockri** [comment]
You can use 'messages' as domain

**Comment by dannyvw** [comment]
It is no longer a problem in master. Dutch translation was not available in 3.5.1

**Pull request closed without merging**
