### PR TITLE
[AdminBundle] Use FOS service ID instead of class

### PR DESCRIPTION
**Pull request by mwoynarski**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | #1975

FOS\UserBundle\Controller\ChangePasswordController requires constructor arguments and is registered as a service by ID rather than class - the routing config needs to call that controller by service ID, rather than class name.

### CODE REVIEW

**Comment by mwoynarski** [comment]
Honestly, I don't know what that change request is asking for.  It's a PR against master, it's a simple yaml change, do with it what you will.

**Comment by sandergo90** [comment]
@mwoynarski bug fixes need to be on the 5.0 branch. That's we @ProfessorKuma is saying this 😉 Can you rebase please ? Thanks!

**Comment by deZinc** [comment]
@mwoynarski If you could rebase your PR on the 5.0 branch we could take a look at this. Thanks.

**Comment by mwoynarski** [comment]
I did.

**Comment by deZinc** [comment]
Are you sure? Because I can see 1154 changed files in this PR. ;)

**Pull request closed without merging**
