### PR TITLE
[AdminBundle] Change admin locale listener priority to after firewall listener

### PR DESCRIPTION
**Pull request by acrobat**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | Related to #1873 #2691 #2714

@dannyvw @krewetka Can you verify is this changes fixes your problem?

### CODE REVIEW

**Review by ProfessorKuma — APPROVED** [review]
Hi @, your PR passed all our requirements.

Thank you for contributing!

**Comment by dannyvw** [comment]
@acrobat This is working for us.

**Review by dannyvw — APPROVED** [review]

**Comment by acrobat** [comment]
Great, thanks for verifying @dannyvw!

**Comment by krewetka** [comment]
It works for me with 5 as well. But to be honest main problem for us was incorrect `default_locale` setting ( which we fixed now)/

When it was incorrect admin panel worked correctly only in English version of content and not Arabic one.

With correct  `default_locale`  it works for me with both priorities 5 and 17.

**Pull request merged**
