### PR TITLE
[AdminListBundle]: don't use query cache when gedmo annotations are used

### PR DESCRIPTION
**Pull request by sandergo90**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets |

When we use for example the Softdeleteable annotation of Gedmo, our admin lists don't work properly. When you go to your admin list which has a Softdeleteable entity and delete an entity from the list, the entity will still remain in the admin list but the entity is already adapted in the database. The query cache causes this problem. Therefor this check is needed. If any Gedmo annotations are used, this can also be the Translatable, drop the query cache.

### CODE REVIEW

**Comment by aistis-** [comment]
I suggest to have an out of the box caching disabling and do not couple it with `Gedmo` annotations. It even could be not annotations, but the mapping could be done via yml or xml as well.

**Comment by sandergo90** [comment]
I think we should use this implementation for Gedmo because it's a common case. If you want to disable the query cache for something else then Gedmo, you can just override the getQuery() method for your admin list configuration and disable the caching there.

**Comment by mlebkowski** [comment]
This shouldn’t be in the core. It covers only one specific use case, it doesn’t fix a problem the core introduces (i.e. the softdeletable is not used in the core), etc. The fix itself does a comparison using a class name and a magic value ("Gedmo"), so produces false positives.

**Comment by sandergo90** [comment]
Yes indeed, it's maybe a to specific use case. I'll just add it to my project, it does not have to be included in the bundles then.

**Pull request closed without merging**
