### PR TITLE
[Documentation] remove addition to upgrade guide that was merged in incorrectly

### PR DESCRIPTION
**Pull request by Numkil**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | #1892

### CODE REVIEW

**Comment by acrobat** [comment]
I think it's best to remove this in the `5.0` branch because it was already included in the `5.0.x` releases (https://github.com/Kunstmaan/KunstmaanBundlesCMS/commit/16b018c560bb821fcbe4b7bb0ace4762b367fe29)

**Comment by Numkil** [comment]
Why though? I know its in the release notes but the actual merge itself was never done. so its confusing people on the master branch now for no reason.

**Comment by acrobat** [comment]
Yeah I know but this was merged somewhere before RC 2 so removing this on the 5.0 branch seems like the best solution to not confuse users who check the upgrade docs in the 5.0 branch

**Comment by Numkil** [comment]
Sorry yes i was confusing 5.0 and 6.0 branch purposes again sorry.

**Pull request merged**
