### PR TITLE
[MediaBundle] Remove empty src set

### PR DESCRIPTION
**Pull request by dannyvw**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | comma separated list of tickets fixed by the PR

Remove duplicate "," to avoid empty srcset.

### CODE REVIEW

**Review by ProfessorKuma — CHANGES_REQUESTED** [review]
Hi @, your PR needs some changes
* It seems that you should have submitted to the latest minor branch.
* This PR seems to need a milestone of a patch release.
* your PR title should look like `[SomeBundle] Fixed some code`

**Review by acrobat — APPROVED** [review]

**Comment by acrobat** [comment]
@dannyvw can you rebase this PR against the 5.5 branch?

**Review by ProfessorKuma — APPROVED** [review]
Hi @, your PR passed all our requirements.

Thank you for contributing!

**Comment by dannyvw** [comment]
@acrobat Done

**Pull request merged**
