### PR TITLE
[WIP] Translation Fixes DE

### PR DESCRIPTION
**Pull request by mablae**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? |no
| Fixed tickets | #1523 #1102 

Please do not merge yet - Work in Progress

### CODE REVIEW

**Comment by mablae** [comment]
@Devolicious 

I used the jms/translation-bundle to extract missing strings. However I noticed a lot of strings that are not translations keys but "english Words" like, "View", "Delete" missing any semantics. 

How should we address this issue?

**Comment by Devolicious** [comment]
@mablae in that case I think that we need some new generic translations that exist in the AdminBundle.

**Comment by sandergo90** [comment]
@mablae Can you check this again ? Because I think the english words are already replaced by translation keys

**Comment by sandergo90** [comment]
@mablae As PR https://github.com/Kunstmaan/KunstmaanBundlesCMS/pull/1651 says, the translation will be soon available with crowdin. If you want to add more german translations, they can be added there.

**Pull request closed without merging**
