### PR TITLE
[AdminListBundle] Fix missing date and time suffixes on form fields #…

### LINKED ISSUE #2513: [AdminListBundle] DateTimeTypeFilter is broken
We've just upgraded the CMS bundles to 5.2.4 and noticed a bug when using the datetime filters. The values of date and time aren't given correctly to the ORM because of the change in the template on commit https://github.com/Kunstmaan/KunstmaanBundlesCMS/pull/2159/commits/554ab55140951a4e65bf716256e9f29a18d3f444.

In src/Kunstmaan/AdminListBundle/Resources/views/FilterType/dateTimeFilter.html.twig the [date] and [time] suffixes are deleted and therefore these aren't available anymore.

### PR DESCRIPTION
**Pull request by lkeijmel**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | fixes #2513

The date and time values weren't posted correctly because the [date] and [time] fieldname suffixes were missing.

### CODE REVIEW

**Comment by acrobat** [comment]
Hi @lkeijmel, thanks for this bugfix. Can you rebase this PR against the 5.3 branch as this is a bugfix. Thanks!

**Comment by lkeijmel** [comment]
@acrobat done

**Comment by acrobat** [comment]
@lkeijmel can you rebase the branch against 5.3 as this PR now includes the commits from master.

**Comment by acrobat** [comment]
@lkeijmel I think something went wrong, now are 60 commits included in this PR. Can you try again? Or otherwise close this PR and create a new one from the 5.3 branch.

**Comment by lkeijmel** [comment]
@acrobat Indeed something went wrong with the rebase, I will close this one and make a new PR

**Pull request closed without merging**
