### PR TITLE
[SensioGeneratorBundle] Typo

### PR DESCRIPTION
**Pull request by OskarStark**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets |

### CODE REVIEW

**Review by ProfessorKuma — CHANGES_REQUESTED** [review]
Hi @, your PR needs some changes
* your PR title should look like `[SomeBundle] Fixed some code`

**Review by ProfessorKuma — APPROVED** [review]
Hi @, your PR passed all our requirements.

Thank you for contributing!

**Comment by acrobat** [comment]
Hi @OskarStark, Thanks for PR. Can you rebase your PR against the 5.6 branch as that is the latest supported version to receive bugfixes.

**Comment by OskarStark** [comment]
Created a new PR via UI in #2796

**Pull request closed without merging**
