### PR TITLE
[AllBundles] Allow next majors of doctrine-bundle and doctrine-migrations-bundle to prepare symfony 5 support

### PR DESCRIPTION
**Pull request by acrobat**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | 

Added a FC layer for doctrine migrations v2

### CODE REVIEW

**Review by ProfessorKuma — APPROVED** [review]
Hi @, your PR passed all our requirements.

Thank you for contributing!

**Comment by acrobat** [comment]
On hold until 6.0 when the deprecated migrations diff command is removed

**Review by ProfessorKuma — CHANGES_REQUESTED** [review]
Hi @, your PR needs some changes
* This PR seems to need a milestone of a minor release.

**Review by ProfessorKuma — APPROVED** [review]
Hi @, your PR passed all our requirements.

Thank you for contributing!

**Review by Numkil — APPROVED** [review]

**Pull request merged**
