### PR TITLE
[AdminBundle] Add indication that page is online/offline

### PR DESCRIPTION
**Pull request by dbeerten**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | #300

### CODE REVIEW

**Comment by jockri** [comment]
@dbeerten Do you have screenshots?

**Comment by dbeerten** [comment]
screen shot 2015-11-20 at 15 58 28

screen shot 2015-11-20 at 15 59 48

**Comment by jockri** [comment]
Nice!

@roderik what do you think? :)

**Comment by roderik** [comment]
:+1:

**Pull request merged**
