### PR TITLE
[AdminListBundle] Fixed doctrine Index for LockableEntity

### PR DESCRIPTION
**Pull request by klopschlike**
Fixed column names in doctrine index

> [Doctrine\DBAL\Schema\SchemaException]
> There is no column with name 'entityId' on table 'kuma_lockable_entity'.

Couldn't create LockableEntity using doctrine:schema:create when using AdminListBundle
Column names are seperated by underscore

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets |

### CODE REVIEW

**Comment by sandergo90** [comment]
Hi @klopschlike ,

Thanks for the pull request. Maybe it's a good thing to also change the column names. Can you add the column name with underscore to entityClass and entityId ?

Thanks !

**Comment by klopschlike** [comment]
I included the column names as requested.

**Comment by sandergo90** [comment]
Perfect! Can you change the base branch to master because 5.0 branch is for BC breaks ;)

**Comment by klopschlike** [comment]
Hey @sandergo90,
I need help understanding github.

Is changing the base branch in github enough? Doing a pull request from 5.0 to master seems very awkward.
Should I submit a new pull request with the changes rebased onto master?

Thank you for your patience!

**Comment by sandergo90** [comment]
Hi @klopschlike,

As you said indeed, you can start a new PR starting from the master branch ;)

**Comment by klopschlike** [comment]
Closed as it is continued in #1654

**Pull request closed without merging**
