### PR TITLE
[TranslatorBundle] change in doctrine querybuilder on php8 systems caused our faulty expression to generate a non working query

### PR DESCRIPTION
**Pull request by Numkil**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets |

### CODE REVIEW

**Comment by jerome2710** [comment]
@Numkil we are currently experiencing the bug resolved in this pull-request. As it is tagged in the 6.2.4 milestone and the latest release is now 6.2.3 from December 15th 2022, could you give us an estimation when 6.2.4 will be released?

**Comment by acrobat** [comment]
@jerome2710 I will push some releases this week!

**Comment by acrobat** [comment]
@jerome2710 [6.2.4](https://github.com/Kunstmaan/KunstmaanBundlesCMS/releases/tag/6.2.4) is released!

**Comment by jerome2710** [comment]
> @jerome2710 [6.2.4](https://github.com/Kunstmaan/KunstmaanBundlesCMS/releases/tag/6.2.4) is released!

@acrobat Great, thanks!

**Pull request merged**
