### PR TITLE
[AllBundles] Quote values (deprecations)

### PR DESCRIPTION
**Pull request by dannyvw**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | yes |
| Fixed tickets |  |

### CODE REVIEW

**Comment by jockri** [comment]
When do you get deprecations from unquoted classnames?
Looks like the unquoted version is also still supported:
http://symfony.com/blog/new-in-symfony-2-8-yaml-deprecations

**Comment by aistis-** [comment]
Yeah, it is supported.

**Comment by dannyvw** [comment]
It is supported (for now), but this PR fixes also scalars that start with a % character http://symfony.com/blog/new-in-symfony-3-1-yaml-deprecations

**Comment by jockri** [comment]
I would not quote the classnames for now. Can you update PR to only quote the scalars that start with %? 
Thanks!

**Comment by dannyvw** [comment]
I don't have time for that now. But in different files we have already quoted the classnames, so this is just a cleanup that straighten all files.

**Comment by Devolicious** [comment]
Closing this since all deprecation issues are already solved.

**Pull request closed without merging**
