### PR TITLE
[AdminBundle] Add brands to font awesome imports

### PR DESCRIPTION
**Pull request by dannyvw**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | #2733

### CODE REVIEW

**Review by ProfessorKuma — CHANGES_REQUESTED** [review]
Hi @, your PR needs some changes
* It seems that you should have submitted to the latest minor branch.
* This PR seems to need a milestone of a patch release.
* your PR title should look like `[SomeBundle] Fixed some code`

**Review by dbeerten — APPROVED** [review]

**Comment by acrobat** [comment]
@dannyvw can you rebase this PR against the 5.5 branch? Thanks!

**Comment by dannyvw** [comment]
@acrobat Done

**Review by ProfessorKuma — APPROVED** [review]
Hi @, your PR passed all our requirements.

Thank you for contributing!

**Comment by acrobat** [comment]
Thanks @dannyvw!

**Pull request merged**
