### PR TITLE
[MenuBundle] Override Gedmo to allow multiple tree roots on menu_id c…

### PR DESCRIPTION
**Pull request by delboy1978uk**
…olumn

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | yes
| Deprecations? | no
| Fixed tickets | https://github.com/Kunstmaan/KunstmaanBundlesCMS/issues/1811

### CODE REVIEW

**Comment by delboy1978uk** [comment]
This causes a BC break - Devs must set the gedmo listener to our one :
```yaml
gedmo.listener.tree:
        class: Kunstmaan\MenuBundle\EventListener\TreeListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]
```

**Comment by delboy1978uk** [comment]
Hello! I didn't want to break the bundles, so I tweaked our changes and made a pull request on the actual package https://github.com/Atlantic18/DoctrineExtensions/pull/1877

**Comment by Numkil** [comment]
Problem was solved in the gedmo repository so no need to do it here anymore.

**Comment by acrobat** [comment]
@Numkil I think the only change we still need of the PR is the `@Gedmo\TreeRoot` annotation on the `menu` propery. https://github.com/Kunstmaan/KunstmaanBundlesCMS/pull/1812/files#diff-c4c919080101e87060c1cfef3bf34597R37

And maybe set the minimum version for gedmo on the version with this fix included?

**Pull request closed without merging**
