### PR TITLE
[AdminBundle] Force dropdown to remain open after selection

### PR DESCRIPTION
**Pull request by dannyvw**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | comma separated list of tickets fixed by the PR

https://select2.org/dropdown#forcing-the-dropdown-to-remain-open-after-selection

### CODE REVIEW

**Review by ProfessorKuma — CHANGES_REQUESTED** [review]
Hi @, your PR needs some changes
* This PR seems to need a milestone of a minor release.

**Review by ProfessorKuma — APPROVED** [review]
Hi @, your PR passed all our requirements.

Thank you for contributing!

**Comment by dbeerten** [comment]
IMO this shouldn't be default behaviour. I think it can be useful for selects that allow multiple values, but not for just a single value.

**Comment by dannyvw** [comment]
@dbeerten This option works only for multiple values. See also the documentation on the provided link.

**Comment by acrobat** [comment]
@dbeerten The change is ok for you?

**Comment by dbeerten** [comment]
> @dbeerten The change is ok for you?

Yes!

**Comment by acrobat** [comment]
Thanks @dannyvw!

**Pull request merged**
