### PR TITLE
[NodeBundle] Don't BC break nodeTranslation introduced when we depreciated the service method

### PR DESCRIPTION
**Pull request by woutervandamme**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | #376

### CODE REVIEW

**Comment by krispypen** [comment]
@roderik :+1:

**Comment by kimausloos** [comment]
The case is wrong, it should be 'nodetranslation', all lowercase.

**Comment by krispypen** [comment]
indeed, not tested? :)

**Comment by kimausloos** [comment]
@krispypen :+1:  for me now :)

**Comment by krispypen** [comment]
@roderik also for me :+1:

**Pull request merged**
