### PR TITLE
[WIP][AdminBundle][PagePartBundle] implement new way to choose pageparts

### PR DESCRIPTION
**Pull request by Numkil**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | no |
| Deprecations? | no |
| Fixed tickets |  |

Allow people to choose between the old select box way of choosing a pagepart
or choose one via a new ui that will show pictures of the respective pageparts
developers can choose to configure their pageparts with a preview url.
The feature is opt-in for now

### CODE REVIEW

**Comment by mlebkowski** [comment]
Could you please add this feature when setting up pageparts using the symfony config as well? I’m talking about the feature introduced in #1109 for defining pageparts in `config.yml` instead of separate yaml files.

This would just require another scalar node here [DependencyInjection/Configuration.php#L34](https://github.com/mlebkowski/KunstmaanBundlesCMS/blob/master/src/Kunstmaan/PagePartBundle/DependencyInjection/Configuration.php#L34) if I’m not mistaken

**Comment by Numkil** [comment]
@mlebkowski Yes i will, thanks for reminding me!

**Comment by wesleylancel** [comment]
@Numkil: nice, this sounds good! Happen to have a screenshot?

**Comment by Numkil** [comment]
@wesleylancel, the layout is still open for debate but this is what I have now. I'm trying to find a balance in between too small screenshots and too huge modal because of large screenshots. 

screen shot 2016-07-27 at 09 34 06
screen shot 2016-07-27 at 09 38 32

**Comment by Numkil** [comment]
This still needs some styling / css work to get everything nice on all screens and views. Maybe one of our frontenders could look at this? 

@KMBenjaminSchodts hint hint if you feel like doing some more bundels stuff.

**Comment by sandergo90** [comment]
@diskwriter hint hint

**Comment by Numkil** [comment]
I will update this PR tonight to get it back up to date with current code. Makes it a bit easier to work on.

**Comment by Numkil** [comment]
@Devolicious @diskwriter Rebased pull request to be up to date again with master and checked that everything still works. 👍

**Comment by sandergo90** [comment]
@Devolicious  @Numkil I've cleaned this PR a little bit and added the styling to it.

Now it will look like this

image

**Pull request merged**
