### PR TITLE
[SensioGeneratorBundle] Fixed typo in form class name

### PR DESCRIPTION
**Pull request by OskarStark**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | no

Replaces #2793

### CODE REVIEW

**Review by ProfessorKuma — CHANGES_REQUESTED** [review]
Hi @, your PR needs some changes
* It seems that our checklist is missing or incomplete

**Comment by OskarStark** [comment]
Fixed

**Review by ProfessorKuma — CHANGES_REQUESTED** [review]
Hi @, your PR needs some changes
* This PR seems to need a milestone of a patch release.

**Review by ProfessorKuma — APPROVED** [review]
Hi @, your PR passed all our requirements.

Thank you for contributing!

**Review by acrobat — APPROVED** [review]

**Comment by acrobat** [comment]
Thanks @OskarStark!

**Pull request merged**
