### PR TITLE
[All Bundles] removed deprecated notices

### PR DESCRIPTION
**Pull request by piotrbelina**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | |no
| Deprecations? | no
| Fixed tickets |

### CODE REVIEW

**Comment by mlebkowski** [comment]
hold on, hold on! `choice_label` for example is only available in Symfony 2.7, this is a breaking change.

**Comment by mlebkowski** [comment]
I guess that changing the FormTypes methods are also a breaking change:
```diff
-    public function setDefaultOptions(OptionsResolverInterface $resolver)
+    public function configureOptions(OptionsResolver $resolver)
```

This way if someone extends `setDefaultOptions` and uses `parent::setDefaultOptions`… ?

**Comment by roderik** [comment]
ow crap

**Comment by roderik** [comment]
@piotrbelina could you check this out?

**Comment by piotrbelina** [comment]
@mlebkowski thank you for noticing it
@roderik it will revert setDefaultOptions and choice_label changes

**Pull request merged**
