### PR TITLE
[KunstmaanAdminBundle]: fix logger

### PR DESCRIPTION
**Pull request by sandergo90**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | #1578

### CODE REVIEW

**Comment by wesleylancel** [comment]
Was already fixed in 5.0 branch: https://github.com/Kunstmaan/KunstmaanBundlesCMS/pull/1516

**Comment by sandergo90** [comment]
@wesleylancel perfect! I thought I saw it already ;)

This maybe needs to be backmerged in the master branch @Devolicious ?

**Comment by sandergo90** [comment]
@Devolicious can you merge the commit for this issue from the 5.0 branch into the master branch to?

**Comment by Devolicious** [comment]
Already fixed from another PR

**Pull request closed without merging**
