### PR TITLE
[AllBundles]: add crowdin as localization project management platform

### PR DESCRIPTION
**Pull request by sandergo90**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | #1649

As suggested in #1649 we have added crowdin as localization project management platform. Some translations are already updated to a better one in this PR. All new translations can be added to the crowdin kunstmaanbundlescms project. More info added to the upgrade guide!

http://translatebundles.kunstmaan.be

TODO'S:

- [x] Add custom domain name for crowdin
- [x] Apply for open source project at crowdin

### CODE REVIEW

**Comment by cv65kr** [comment]
@sandergo90 great job!

**Comment by sandergo90** [comment]
@cv65kr already doing a good job! 😉

**Comment by cv65kr** [comment]
@sandergo90, can You explain me difference between feature-crowdin and separately bundles? Check out my screenshot.
crowdin

**Comment by sandergo90** [comment]
@cv65kr That's because my first try was by doing it with the crowdin CLI. But later on I activated the github integration. Currently the translations are living in my feature-crowdin branch. But when this PR is merged to master, only "master" will appear in the translations list 😉

**Pull request merged**
