### PR TITLE
[AllBundles] Enhancement: Remove .idea/ and .DS_Store from .gitignore files

### PR DESCRIPTION
**Pull request by OskarStark**
Those should be ignored using the users global .gitignore file.

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | --

### CODE REVIEW

**Review by ProfessorKuma — CHANGES_REQUESTED** [review]
Hi @, your PR needs some changes
* It seems that our checklist is missing or incomplete

**Comment by OskarStark** [comment]
Rebased @acrobat

**Comment by OskarStark** [comment]
Shall I close this PR @acrobat ?

**Comment by acrobat** [comment]
Sorry for the delay, thanks @OskarStark!

**Review by acrobat — APPROVED** [review]

**Comment by OskarStark** [comment]
No problem, thank you!

**Pull request merged**
