### PR TITLE
[SensiolabsInsight] - remove user .gitignore files

### PR DESCRIPTION
**Pull request by delboy1978uk**
Should be in global gitignore. Create and use it like so:
```
touch ~/.gitignore_global
git config --global core.excludesfile ~/.gitignore_global .
```
Then add .idea to the file

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | https://github.com/Kunstmaan/KunstmaanBundlesCMS/issues/1685

### CODE REVIEW

**Comment by delboy1978uk** [comment]
ah I didn't see that one! Ok give me two minutes!

**Comment by delboy1978uk** [comment]
😑 lol, ok, i'll rebase this too!

**Comment by mlebkowski** [comment]
So SensioInsights is ignoring the fact that about half of the developers ever checking out this repo will use either PHPStorm or a mac, hence having both of those files in the repo? So instead making their life easier by having those „user specific” entries, you instead want every dev to have a custom setup step? In my opinion this insight is stupid. It doesn’t hurt anyone to have those two lines there.

OTOH, every mac user should have `.DS_Store` in their global ignore, as well as every PHPStorm user probably has `.idea` there… ;) 

As for your snippet, I don’t see a reason to rename the global ignore file. You can just do this instead:

```
grep ".idea" ~/.gitignore >/dev/nul || echo .idea | tee -a ~/.gitignore 
grep ".DS_Store" ~/.gitignore >/dev/nul || echo .DS_Store | tee -a ~/.gitignore 
```

So if a user already have their `~/.gitignore` (the default path), you can just append your entries if they don’t exist.

**Comment by delboy1978uk** [comment]
I like being verbose about my files and classnames etc, hence the _global. Just a suggestion! 
I guess most people here are devs smart enough to realise that ~/.gitignore would be user specific and global. :-)

**Comment by sandergo90** [comment]
@mlebkowski welcome back ! 😉 It's maybe a stupid suggestion of Insights but I can see why. It's a user specific think so it shouldn't be in our project IMHO.

**Comment by mlebkowski** [comment]
hi @sandergo90, I never went anywhere, I were just lurking ;)

@delboy1978uk, ok I agree that the devs should be smart enough to interpret. point taken.

**Pull request merged**
