### PR TITLE
[NodeBundle] Added support for locale domains

### PR DESCRIPTION
**Pull request by yoshz**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | #109 

This pull request adds support for different domains for each locale (as mentioned in #109).

Users have to configure `localedomains` parameter in parameters.yml like:
```
localedomains:
  domain.com: en
  domain.fr: fr
  domain.nl: nl
  domain.de: de
```
The parameter is not mandatory for now, so it shouldn't break existing installations.

I'm not a big fan of getting parameters from the container directly, but this was already the case for multilanguage and defaultlocale so I used the same method.

**Other points to think about:**
- [ ] Refactor multilanguage parameter. Both parameters could be set but work independently.
- [ ] Update documentation
- [ ] Add parameter to standard edition

### CODE REVIEW

**Comment by roderik** [comment]
@kimausloos @jockri let's compare this with our own plan and see how to learn form this approach

**Comment by yoshz** [comment]
Keep me updated. Any feedback is welcome!

**Comment by yoshz** [comment]
@roderik It would be nicer to have some kind of multidomain support.
If you can assign one or more hostnames to a root node it also fits the solution for different locale domains.

**Comment by roderik** [comment]
I think our version will be ready next week, it goed quite a bit further than your proposal and will feature:

* domains to rootnodes mapping (so you can do multisite)
* extend locale to country-locale (nl_NL nl_BE -> both dutch, but different writingstyle and country info)
* map a domain to a locale -> http://mysite.nl/ (single lang, nl_NL locale)  http://mysite.be/nl http://mysite.be/fr (multi lang, nl_BE and fr_BE locales)

And completely configured in a YAML file

**Comment by roderik** [comment]
The pull request is up, check it out #633

**Comment by yoshz** [comment]
Looks like exactly what we need :+1:

**Pull request closed without merging**
