### PR TITLE
[NodeBundle][AdminListBundle][PagePartBundle] Check if admin type is fqcn

### PR DESCRIPTION
**Pull request by dannyvw**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Fixed tickets | #1175 |

### CODE REVIEW

**Comment by mlebkowski** [comment]
Form Type could have its dependencies, so `new $formType` can fail with a fatal error.

**Comment by dannyvw** [comment]
True, but all form types are changed because passing parameters is deprecated. See also PR https://github.com/Kunstmaan/KunstmaanBundlesCMS/pull/950

**Comment by mlebkowski** [comment]
@dannyvw, I don’t see how’s that related. I’m just staying that instead of:

```
$formType; /// class name
$form = new $formType;
/// …
$fqcn = get_class($form);
```

you could simply:

```
$formType; /// class name
/// ...
$fqcn = $formType;
```

**Comment by dannyvw** [comment]
@mlebkowski, I think that i know what you mean, but $formType can have different values like: 
```
// FQCN
AdminFormType::class
// Object
new AdminFormType() 
// service
'service.admin_form_type'
```
and yes ```$formType = new $formType;``` is then unnecessary because it's already an FQCN.

We can also do something like this
```
        $formType = $configurator->getAdminType($helper);
        $formFqn = is_object($formType) ? get_class($formType) : $formType;
        if (!is_object($formType) && is_string($formType)) {
            if ($this->container->has($formType)) {
                $formFqn = get_class($this->container->get($formType));
            }
        }
```

**Comment by mlebkowski** [comment]
Yes, that’s what I was talking about.

**Comment by dannyvw** [comment]
I have updated the pr's

**Comment by aistis-** [comment]
Looks like there is some duplicated code. Could you extract it to one place and reuse it?

**Comment by dannyvw** [comment]
@aistis- I added a helper for getting the fqcn and merged this branch into the sf3 branch, see #1263

**Comment by aistis-** [comment]
I think it is a good fix for 3.x Kunstmaan version, but I suggest to drop BC for the old strategy on 4.x as it is for Symfony 3+ version only.

**Comment by Devolicious** [comment]
This was covered in #1348 so I'll close this.

**Pull request closed without merging**
