### PR TITLE
[AllBundles] entity tests 100% covered

### PR DESCRIPTION
**Pull request by delboy1978uk**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | improvement for development
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | none - just getting code coverage up!

### CODE REVIEW

**Comment by delboy1978uk** [comment]
I'll be adding more commits in here with more tests, but I guess we can merge this whenever since it's only tests being added

**Comment by delboy1978uk** [comment]
I'll find and replace all of the KunstmaanTesting stuff once all the existing tests have been migrated over :-)

**Comment by cv65kr** [comment]
@delboy1978uk can You squash commits?

**Comment by delboy1978uk** [comment]
Yes I'll squash the commits once each bundle has been moved across and I've changed the namespace

**Comment by delboy1978uk** [comment]
All tests moved, all `@covers` annotations removed, entity tests added, and all tests now live in the `Tests\Kunstmaan` namespace.

**Comment by delboy1978uk** [comment]
@Numkil  ^ :-)

**Comment by acrobat** [comment]
Why do we move the tests to a separate folder/namespace? It seems more logical to me to keep the tests for each bundle in each bundle dir/namespace. It is no problem for phpunit to run tests in subfolders and if we enable the subtree split again to have the separate packages available, the tests need to be in the packages itself.

**Comment by delboy1978uk** [comment]
Hi @Devolicious there's a fake entity i was using in the test suite so i couljd test an abstract class, looks like there are extra methods in the master branch, you probably just need to add an empty method to it I'm guessing

**Comment by Devolicious** [comment]
Hi @delboy1978uk,

Yes I'm currently fixing it but there were some other changes as well because of the switch from 4.0 to master branch. I'm gonna open a new PR that starts from your branch as base and then all the necessary patches on top of that.

**Comment by Devolicious** [comment]
Continued in #1924

**Comment by Devolicious** [comment]
@delboy1978uk You should subcribe on https://kumathon.kunstmaan.be/

**Comment by delboy1978uk** [comment]
@Devolicious i think i already did

**Pull request closed without merging**
