### PR TITLE
[ConfigBundle] Check if admin type is fqcn

### PR DESCRIPTION
**Pull request by dannyvw**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Fixed tickets | #1175 |

### CODE REVIEW

**Comment by aistis-** [comment]
Need this fix! :)

relates to #1262

**Comment by aistis-** [comment]
@dannyvw @jockri What if refactor all forms to use fqcn instead of keeping BC when Type object is passed and then trying to compute fqcn by `get_class($typeObject)`? This branch is for Symfony 3 and it dropped a BC for deprecated strategy. I suggest do the same, as the code will come cleaner, more convenient. This legacy workaround causes some issue for the form with injected parameters (see https://github.com/Kunstmaan/KunstmaanBundlesCMS/pull/1310) via constructor instead of using *form options*.

What do you think guys?

**Comment by dannyvw** [comment]
@aistis- +1 for dropping BC for the old strategy. But before we can drop this, all implementations must be changed.

**Comment by aistis-** [comment]
Yes, indeed :)

**Comment by Devolicious** [comment]
This was covered in #1348 so I'll close this.

**Pull request closed without merging**
