### PR TITLE
Set default list template in constructor instead of hard coded getter

### PR DESCRIPTION
**Pull request by delboy1978uk**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | #1636

### CODE REVIEW

**Comment by sandergo90** [comment]
@delboy1978uk can you change the PR to the master branch ?

**Comment by Devolicious** [comment]
@delboy1978uk could you please also fix the issue that SensioLabsInsight is showing?  https://insight.sensiolabs.com/projects/34aece18-3640-47ea-8e9f-96b79919905b/analyses/44?status=commit

There is an ```abstract function``` at the bottom of the ```AbstractPageAdminListConfigurator``` that should be ```abstract public function```

Thx!

**Comment by delboy1978uk** [comment]
I clicked that sensio link, but it told me "This analysis is not available anymore. We only keep the past 5 analyses on public projects for users on a free plan."

May I recommend Scrutinizer-CI? There is no such restriction for open sourced projects on Github!
https://scrutinizer-ci.com

**Comment by sandergo90** [comment]
@delboy1978uk we already fixed the symfony cmf stuff and the Travis.yml. You should rebase to master Again ;)

**Comment by delboy1978uk** [comment]
I tried rebasing, it said i was up to date! So I have set the composer.json the same as what the conflict was showing was up here

**Comment by sandergo90** [comment]
Did you pull origin master first?

**Comment by delboy1978uk** [comment]
yeah i'm up to date!

**Comment by sandergo90** [comment]
@delboy1978uk Can you try to rebase to master again ? The symfony CMF should already be fixed there.

**Comment by sandergo90** [comment]
Actually @Devolicious this needs to be on the 5.0 branch because it's bug fix. ?

**Pull request merged**
