### PR TITLE
[MediaBundle] Position sort by and limit

### LINKED ISSUE #2736: [MediaBundle] Position button media overview
Can we position the buttons next to each other? Or something else to make it cleaner.

media-overview

### PR DESCRIPTION
**Pull request by dannyvw**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | fixes #2736

Screenshot from 2020-09-21 11-58-38

### CODE REVIEW

**Review by ProfessorKuma — CHANGES_REQUESTED** [review]
Hi @, your PR needs some changes
* your PR title should look like `[SomeBundle] Fixed some code`

**Review by ProfessorKuma — APPROVED** [review]
Hi @, your PR passed all our requirements.

Thank you for contributing!

**Review by ProfessorKuma — CHANGES_REQUESTED** [review]
Hi @, your PR needs some changes
* This PR seems to need a milestone of a minor release.

**Review by ProfessorKuma — APPROVED** [review]
Hi @, your PR passed all our requirements.

Thank you for contributing!

**Review by Numkil — APPROVED** [review]

**Review by acrobat — APPROVED** [review]

**Comment by acrobat** [comment]
Thanks @dannyvw!

**Pull request merged**
