### PR TITLE
[AllBundles] Fix: Codestyle

### PR DESCRIPTION
**Pull request by OskarStark**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | --

It turns out, that StyleCi only checks the touched files in a PR, so lets run it manually once.

Lets see if StyleCi will report something back, because based on a chat with @acrobat the configs between StyleCi and local PHP-CS-Fixer are different.

### CODE REVIEW

**Review by ProfessorKuma — CHANGES_REQUESTED** [review]
Hi @, your PR needs some changes
* your PR title should look like `[SomeBundle] Fixed some code`

**Review by ProfessorKuma — APPROVED** [review]
Hi @, your PR passed all our requirements.

Thank you for contributing!

**Comment by acrobat** [comment]
@OskarStark can you rebase this PR, there are some conflicts are merges of your other pr's.

**Comment by OskarStark** [comment]
> @OskarStark can you rebase this PR, there are some conflicts are merges of your other pr's.

Sure thing

**Comment by OskarStark** [comment]
Done, please merge this one first, I will rebase all "feature" PR's on top of this 👍

**Comment by acrobat** [comment]
Thanks @OskarStark!

**Pull request merged**
