### PR TITLE
[AdminBundle] Show list of available groups when creating a new admin user via the console 

### PR DESCRIPTION
**Pull request by woutervandamme**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | #317

When creating a new user in the console, you no longer have to type the groups, you can just select them form a list.

### CODE REVIEW

**Comment by roderik** [comment]
@krispypen :+1:

**Comment by jockri** [comment]
Does the developer needs te select the groups by entering the numbers?

**Comment by woutervandamme** [comment]
A list shows up from which you can select multiple options.

screen shot 2015-04-14 at 09 47 39

**Comment by jockri** [comment]
Ok, perfect!

**Pull request merged**
