### PR TITLE
[NodeBundle] add button to menu so pages are saved when published

### PR DESCRIPTION
**Pull request by woutervandamme**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets |  #293 

I've added a "save on publish" button to the menu.

 Another option would be to show a popup when publishing a page that tells the user that the page has not yet been saved.

- [ ] feedback

### CODE REVIEW

**Comment by denbatte** [comment]
The ideal solution would be to just save on publish.
Adding a extra option to the menu just adds complexity imo.
I don't know if a "are you sure" modal window is such a good solution.
Maybe we should have a talk about this in the next backend meeting?

**Comment by krispypen** [comment]
@woutervandamme these buttons should be there: cancel - save - publish now - publish later 

and the "save",  "publish now" and "publish later" should save the page "now"

**Comment by roderik** [comment]
@denbatte werk jij af? :)

**Comment by FVKVN** [comment]
No validation on page publish, this saves and publishes the page even when there are blank required fields

**Comment by jockri** [comment]
When you have unsaved pageparts and you click the publish button, a popup should appear.
Will create issue for this.

**Pull request closed without merging**
