### PR TITLE
[AdminBundle] Fix admin sidebar when NodeBundle is not used

### PR DESCRIPTION
**Pull request by jockri**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets |

### CODE REVIEW

**Comment by wimvds** [comment]
As is, this will break all sites. It needs a better solution then this.

**Comment by jockri** [comment]
This will not break all site. I just used the same check like in the main layout.html.Twig: https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/master/src/Kunstmaan/AdminBundle/Resources/views/Default/layout.html.twig#L27
The variable is set in the Nodebundle: https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/7b216e569f05a14b1df597b667474a3994e80d0f/src/Kunstmaan/NodeBundle/DependencyInjection/KunstmaanNodeExtension.php#L44

I agree that we should find a better solution for the variable, but for the moment it is not possible to remove the NodeBundle from the stack without this quick change.

**Comment by wimvds** [comment]
Ok, didn't know about that global. The whole sidebar handling in the admin still needs a better solution though...

**Comment by krispypen** [comment]
@roderik :+1:

**Pull request merged**
