### PR TITLE
Require at least PHP 5.4

### PR DESCRIPTION
**Pull request by wimvds**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | yes
| Fixed tickets | 

Since PHP 5.3 is no longer maintained, we decided to drop PHP 5.3 support (if you're still using it : you *really* should upgrade!).

### CODE REVIEW

**Comment by roderik** [comment]
:+1:

**Comment by krispypen** [comment]
@wimvds can you also update the .travis.yml file in the root folder?

**Comment by krispypen** [comment]
we should also update the requirements here: http://bundles.kunstmaan.be/documentation

**Comment by roderik** [comment]
@krispypen these requirements are parsed from here: https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/master/docs/03-01-system-requirements.md Updates should be part of the merge request

**Pull request merged**
