### PR TITLE
[RedirectBundle]: add note to redirect

### PR DESCRIPTION
**Pull request by sandergo90**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | #1411

### CODE REVIEW

**Comment by mlebkowski** [comment]
Is this a breaking change? it requires database migration

**Comment by sandergo90** [comment]
@mlebkowski a new field in an entity is not a breaking change I think? It requires to execute a diff and a migrated indeed. But is it therefore a breaking change?

**Comment by wesleylancel** [comment]
@sandergo90 @mlebkowski: I think it is, because it requires a manual action (generating the migration) if you don't want your code to break...

**Comment by mlebkowski** [comment]
I honestly don’t know. For me it’s a minor change as long as it’s clearly stated in the changelog/migration guide.  It won’t break any existing application code or libraries (since the field is nullable), and it’s a trivial fix

**Comment by Devolicious** [comment]
Imho it's not breaking. There is no code that needs fixing. Doing a migration after installing new features is rather normal I think.

**Comment by sandergo90** [comment]
@Devolicious Upgrade guide added

**Pull request merged**
