### PR TITLE
[SeoBundle] Refactor seo description to be longer according to google's new length

### PR DESCRIPTION
**Pull request by rebelchris**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    |no
| Deprecations? |no
| Fixed tickets | #1779

### CODE REVIEW

**Comment by DBuit** [comment]
@Numkil when can we use this fix would be really useful? can this be released in 4.1.1 in short term? My customers are asking me why they can't use the longer meta description...

**Comment by Numkil** [comment]
@DBuit Official release for Bundles 4.1.1  will be at the end of this month. I am sure this PR will be merged in by then.

**Comment by Devolicious** [comment]
Hi @rebelchris,

Your PR is ok but please read our contribution guide to make sure you submit it correctly for you next contribution. Your title should always start with the bundle your work applies to. I will change it for you but soon @ProfessorKuma will nag you about it :) How to submit can be found here https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/master/docs/99-02-pull-requests.md#step-4-send-a-pull-request or on the link provided when you submit the PR.

**Comment by rebelchris** [comment]
@Devolicious Thanks, i tried to follow the document you provided, hence forgot this step, will keep in mind next time.
Thanks for the help this time.

**Pull request merged**
