### PR TITLE
[ArticleBundle] Enhancement: Streamline tests

### PR DESCRIPTION
**Pull request by OskarStark**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  |no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | --

This PR

* [x] is based on https://github.com/Kunstmaan/KunstmaanBundlesCMS/pull/2813#issuecomment-722183497
* [x] removes useless comments
* [x] fixes namespaces
* [x] removes `unit` folder to not violate PSR-4

### CODE REVIEW

**Review by ProfessorKuma — CHANGES_REQUESTED** [review]
Hi @, your PR needs some changes
* This PR seems to need a milestone of a patch release.

**Review by ProfessorKuma — APPROVED** [review]
Hi @, your PR passed all our requirements.

Thank you for contributing!

**Review by acrobat — APPROVED** [review]

**Comment by OskarStark** [comment]
Rebased

**Comment by acrobat** [comment]
Thanks @OskarStark!

**Pull request merged**
