### PR TITLE
Allow PHP 7.2 in Travis

### PR DESCRIPTION
**Pull request by cv65kr**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | no

### CODE REVIEW

**Comment by sandergo90** [comment]
@cv65kr Can you check why travis is failing ? Thanks

**Comment by cv65kr** [comment]
@sandergo90, after many tries, now Travis passed success PHP 7.2. My solution is not perfect, it's something wrong with ```NativeFileSessionHandler``` and PHP 7.2.
Look at Xdebug trace:
```
PHP Warning:  ini_set(): Headers already sent. You cannot change the session module's ini settings at this time in /home/travis/build/Kunstmaan/KunstmaanBundlesCMS/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/NativeFileSessionHandler.php on line 52
PHP Stack trace:
PHP   1. {main}() /home/travis/build/Kunstmaan/KunstmaanBundlesCMS/vendor/phpunit/phpunit/phpunit:0
PHP   2. PHPUnit_TextUI_Command::main() /home/travis/build/Kunstmaan/KunstmaanBundlesCMS/vendor/phpunit/phpunit/phpunit:52
PHP   3. PHPUnit_TextUI_Command->run() /home/travis/build/Kunstmaan/KunstmaanBundlesCMS/vendor/phpunit/phpunit/src/TextUI/Command.php:116
PHP   4. PHPUnit_TextUI_TestRunner->doRun() /home/travis/build/Kunstmaan/KunstmaanBundlesCMS/vendor/phpunit/phpunit/src/TextUI/Command.php:186
PHP   5. PHPUnit_Framework_TestSuite->run() /home/travis/build/Kunstmaan/KunstmaanBundlesCMS/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:517
PHP   6. PHPUnit_Framework_TestResult->startTestSuite() /home/travis/build/Kunstmaan/KunstmaanBundlesCMS/vendor/phpunit/phpunit/src/Framework/TestSuite.php:666
PHP   7. TestListener->startTestSuite() /home/travis/build/Kunstmaan/KunstmaanBundlesCMS/vendor/phpunit/phpunit/src/Framework/TestResult.php:359
PHP   8. AppKernel->boot() /home/travis/build/Kunstmaan/KunstmaanBundlesCMS/TestListener.php:37
PHP   9. AppKernel->initializeContainer() /home/travis/build/Kunstmaan/KunstmaanBundlesCMS/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:137
PHP  10. ContainerB1ey3s8\appPhpunitDebugProjectContainer->get() /home/travis/build/Kunstmaan/KunstmaanBundlesCMS/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:673
PHP  11. ContainerB1ey3s8\appPhpunitDebugProjectContainer->load() /home/travis/build/Kunstmaan/KunstmaanBundlesCMS/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php:297
PHP  12. require() /home/travis/build/Kunstmaan/KunstmaanBundlesCMS/src/Kunstmaan/TranslatorBundle/Tests/app/cache/phpunit/ContainerB1ey3s8/appPhpunitDebugProjectContainer.php:776
PHP  13. Symfony\Component\HttpKernel\CacheWarmer\CacheWarmerAggregate->__construct() /home/travis/build/Kunstmaan/KunstmaanBundlesCMS/src/Kunstmaan/TranslatorBundle/Tests/app/cache/phpunit/ContainerB1ey3s8/getCacheWarmerService.php:16
PHP  14. ContainerB1ey3s8\appPhpunitDebugProjectContainer->{closure:/home/travis/build/Kunstmaan/KunstmaanBundlesCMS/src/Kunstmaan/TranslatorBundle/Tests/app/cache/phpunit/ContainerB1ey3s8/getCacheWarmerService.php:8-16}() /home/travis/build/Kunstmaan/KunstmaanBundlesCMS/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/CacheWarmer/CacheWarmerAggregate.php:29
PHP  15. ContainerB1ey3s8\appPhpunitDebugProjectContainer->load() /home/travis/build/Kunstmaan/KunstmaanBundlesCMS/src/Kunstmaan/TranslatorBundle/Tests/app/cache/phpunit/ContainerB1ey3s8/getCacheWarmerService.php:10
PHP  16. require() /home/travis/build/Kunstmaan/KunstmaanBundlesCMS/src/Kunstmaan/TranslatorBundle/Tests/app/cache/phpunit/ContainerB1ey3s8/appPhpunitDebugProjectContainer.php:776
PHP  17. ContainerB1ey3s8\appPhpunitDebugProjectContainer->load() /home/travis/build/Kunstmaan/KunstmaanBundlesCMS/src/Kunstmaan/TranslatorBundle/Tests/app/cache/phpunit/ContainerB1ey3s8/getValidator_Mapping_CacheWarmerService.php:8
PHP  18. require() /home/travis/build/Kunstmaan/KunstmaanBundlesCMS/src/Kunstmaan/TranslatorBundle/Tests/app/cache/phpunit/ContainerB1ey3s8/appPhpunitDebugProjectContainer.php:776
PHP  19. ContainerB1ey3s8\appPhpunitDebugProjectContainer->getKunstmaanTranslator_DatacollectorService() /home/travis/build/Kunstmaan/KunstmaanBundlesCMS/src/Kunstmaan/TranslatorBundle/Tests/app/cache/phpunit/ContainerB1ey3s8/getValidator_BuilderService.php:29
PHP  20. ContainerB1ey3s8\appPhpunitDebugProjectContainer->getKunstmaanTranslator_Service_Translator_TranslatorService() /home/travis/build/Kunstmaan/KunstmaanBundlesCMS/src/Kunstmaan/TranslatorBundle/Tests/app/cache/phpunit/ContainerB1ey3s8/appPhpunitDebugProjectContainer.php:1714
PHP  21. ContainerB1ey3s8\appPhpunitDebugProjectContainer->getSessionService() /home/travis/build/Kunstmaan/KunstmaanBundlesCMS/src/Kunstmaan/TranslatorBundle/Tests/app/cache/phpunit/ContainerB1ey3s8/appPhpunitDebugProjectContainer.php:1760
PHP  22. ContainerB1ey3s8\appPhpunitDebugProjectContainer->getSession_Storage_NativeService() /home/travis/build/Kunstmaan/KunstmaanBundlesCMS/src/Kunstmaan/TranslatorBundle/Tests/app/cache/phpunit/ContainerB1ey3s8/appPhpunitDebugProjectContainer.php:907
PHP  23. ContainerB1ey3s8\appPhpunitDebugProjectContainer->getSession_HandlerService() /home/travis/build/Kunstmaan/KunstmaanBundlesCMS/src/Kunstmaan/TranslatorBundle/Tests/app/cache/phpunit/ContainerB1ey3s8/appPhpunitDebugProjectContainer.php:2365
PHP  24. Symfony\Component\HttpFoundation\Session\Storage\Handler\NativeFileSessionHandler->__construct() /home/travis/build/Kunstmaan/KunstmaanBundlesCMS/src/Kunstmaan/TranslatorBundle/Tests/app/cache/phpunit/ContainerB1ey3s8/appPhpunitDebugProjectContainer.php:2335
PHP  25. ini_set() /home/travis/build/Kunstmaan/KunstmaanBundlesCMS/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/NativeFileSessionHandler.php:52
```
Any ideas?

**Comment by sandergo90** [comment]
@Devolicious any ideas ?

**Comment by sandergo90** [comment]
@cv65kr I think we should allow it for now. @acrobat do you have any other ideas?

**Comment by acrobat** [comment]
👍I will also spend some time during the hackathon testing/fixing the 7.2 build!

**Comment by sandergo90** [comment]
Awesome!

**Pull request closed without merging**
