### PR TITLE
[AdminBundle] Fix fosuser bundle inheritance deprecation

### LINKED ISSUE #1599: Symfony bundle inheritance will be deprecated in 3.4
See https://github.com/symfony/symfony/issues/24048 for more information

### PR DESCRIPTION
**Pull request by acrobat**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | improvements
| BC breaks?    | no
| Deprecations? | yes
| Fixed tickets | closes #1599 

Removed the parent bundle method and added our views path to the `@FOSUser` twig namespace. Also fixed some templates that were renamed in fosuserbundle

### CODE REVIEW

**Comment by sandergo90** [comment]
@acrobat it's a bug fix so needs to be on 5.0 branch.

**Comment by acrobat** [comment]
ok 👍 will rebase this onto 5.0

**Comment by acrobat** [comment]
@sandergo90 done!

**Comment by acrobat** [comment]
As discussed with @sandergo90 we keep this change for the 5.1 release as it's not a "real" bugfix

**Pull request merged**
