### PR TITLE
[AdminBundle] Fix toolbar version checker

### PR DESCRIPTION
**Pull request by cv65kr**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | #1713

### CODE REVIEW

**Comment by sandergo90** [comment]
@cv65kr I think we should also check why this template is still rendered when the version checker is disabled. This data check is already a good thing, but it shouldn't be rendered at all.

**Comment by cv65kr** [comment]
@sandergo90, It's weird
If i change this part in ```Kunstmaan/AdminBundle/Resources/views/Toolbar/toolbar.html.twig```:
```
{% for collector in collectors %}
        {{ block_render(collector.template, 'toolbar', collector.collectData()) }}
    {% endfor %}
```
to
```
    {% for collector in collectors %}
        {% if collector.isEnabled() %}
            {{ block_render(collector.template, 'toolbar', collector.collectData()) }}
        {% endif %}
    {% endfor %}
```
that should be correct. But ignore these part, what is wrong?

**Comment by sandergo90** [comment]
@cv65kr after looking further in it, your PR seems like the correct solution. When the isEnabled() function returns false, it will pass an empty array as data. So the check for empty date in the twig file is enough.

**Comment by Numkil** [comment]
@cv65kr thanks!

**Pull request merged**
