### PR TITLE
[SeoBundle]: change meta length

### PR DESCRIPTION
**Pull request by sandergo90**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | 

https://www.seoinc.com/seo-blog/google-increases-title-meta-description-length/

### CODE REVIEW

**Comment by mlebkowski** [comment]
It feels shortsighted to limit the field to what google thinks is useful. It’s called `meta_title`, not `google_title`, there are other search engines and robots out there… I suggest a length of 255.

**Comment by sandergo90** [comment]
That's even better indeed. Maybe we should add a question mark next to the input field with some more information ?

**Comment by sandergo90** [comment]
@mlebkowski i've checked some resources and all common search engines limit their meta title around 70 characters.

https://www.sagerock.com/blog/title-tag-meta-description-length/

So I would suggest to set the limit to 70 characters. 255 is to much for a meta title.

**Comment by mlebkowski** [comment]
Why should a CMS limit this? If I wanted to use 71 characters, because I wanted to end a sentence, I could not do it?

**Comment by sandergo90** [comment]
Real clients who are using the CMS want to have a limitation on it. The people who are doing the content input do not know how many characters they can enter. I think by limiting this, it will be clearer.

**Comment by mlebkowski** [comment]
Your argument suggests that I am not a real client. ;) Wouldn’t not limiting the field in a database and adding a `max_length` config value with a sane default be a good compromise?

**Comment by sandergo90** [comment]
Yes I call us Developer ;) So we remove the assert on the entity and add a constraint in the form type that has a max_length value coming from the config ?

**Comment by mlebkowski** [comment]
yes, sandergo, that would be the idea. but as much as I think about it, the more I’m convinced it isn’t worth the effort :)

**Comment by sandergo90** [comment]
@mlebkowski I was just thinking the same 😆 . Maybe we can remove the assert on the entity and leave it at 70 on the form type and add a constraint there. When someone wants to override this, they can override the form type.

**Pull request merged**
