### PR TITLE
[NodeBundle] Fix translation typo

### PR DESCRIPTION
**Pull request by poveu**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets |

### CODE REVIEW

**Comment by acrobat** [comment]
Hi @poveu , thanks for this translation fix. Can you rebase this PR against the 5.3 branch as this is a bugfix? Thanks!

**Comment by poveu** [comment]
I hope renaming my branch isn't necessary?
This is what happens when you try to quickly create a simple PR through GitHub website 😛

**Comment by acrobat** [comment]
@poveu I've switched the base branch to 5.3, but this branch was not correctly rebased. Can you try it again? Or otherwise close this PR and open a new one directly created from the 5.3 branch

**Comment by poveu** [comment]
> @poveu I've switched the base branch to 5.3, but this branch was not correctly rebased. Can you try it again? Or otherwise close this PR and open a new one directly created from the 5.3 branch

Done in new PR https://github.com/Kunstmaan/KunstmaanBundlesCMS/pull/2536

**Pull request closed without merging**
