### PR TITLE
[AllBundles] Fixed switching domain

### PR DESCRIPTION
**Pull request by dannyvw**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | yes
| Deprecations? | no
| Fixed tickets | #1296

### CODE REVIEW

**Comment by mlebkowski** [comment]
Guys, please. Changing an interface is a BC break.

**Comment by sandergo90** [comment]
@dannyvw Our application breaks with your pull request. In the selectLink.html.twig template you have removed the switched_host variable.

`{% if is_multidomain_site() %}
        {% if switched_host_is_current() %}
            {% set slug = "[%s]" | format("NT" ~ item.nt_id) %}
        {% else %}
            {% set slug = "[%s:%s]" | format(switched_host.id, "NT" ~ item.nt_id) %}
        {% endif %}
    {% else %}
        {% set slug = "[%s]" | format("NT" ~ item.nt_id) %}
    {% endif %}`

When you open the URL Chooser now, you will get a undefined variable switched_host

**Comment by sandergo90** [comment]
@jockri can you revert this? This is not the correct solution..

**Comment by dannyvw** [comment]
@sandergo90 @jockri If you revert this pull request then you can not switch from domain.

I suggest to change only the changes in selectLink.html.twig or fix the URL Chooser.

**Comment by sandergo90** [comment]
@dannyvw I've created a new pull request to fix the issue. 

https://github.com/Kunstmaan/KunstmaanBundlesCMS/pull/1346

**Comment by dannyvw** [comment]
@sandergo90 @jockri Looks good, but the PR is now completely reverted which is not good.

As example the getFullHostConfig method is now missing.. this bug is introduced in https://github.com/Kunstmaan/KunstmaanBundlesCMS/pull/1225. So please revert this pull request and add the fix from #1346

**Pull request merged**
