### PR TITLE
[MediaBundle] Don't show filesize if null

### PR DESCRIPTION
**Pull request by dannyvw**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | #1566

### CODE REVIEW

**Comment by Devolicious** [comment]
@dannyvw You should submit bugfix PR's to the latest minor version branch, in this case that's 4.0.

https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/master/docs/99-02-pull-requests.md#select-the-correct-branch-for-your-pull-request

**Comment by dannyvw** [comment]
@Devolicious Done

**Comment by delboy1978uk** [comment]
This is still the case for me (working on 5.0 branch) - Should we cherry pick it into a fix branch from 5.0 too?

**Comment by sandergo90** [comment]
@delboy1978uk 4.0 will be up-merged into the master branch and then again master into the 5.0 branch.

**Pull request merged**
