### PR TITLE
[AllBundles] Enhancement: Add GithubAction to run PHP-CS-Fixer

### PR DESCRIPTION
**Pull request by OskarStark**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | --

It will run first if the workflow file is merged.
You can check the run here: https://github.com/OskarStark/KunstmaanBundlesCMS/pull/1

### CODE REVIEW

**Review by ProfessorKuma — APPROVED** [review]
Hi @, your PR passed all our requirements.

Thank you for contributing!

**Comment by OskarStark** [comment]
Oh they are failing

**Comment by OskarStark** [comment]
Rebased

**Comment by acrobat** [comment]
I'm closing this PR for now as we have FlintCI now. In the future we might fully switch to github actions but the setup is ok for now.

**Pull request closed without merging**
