### PR TITLE
[NodeBundle] unused class property

### PR DESCRIPTION
**Pull request by delboy1978uk**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | https://github.com/Kunstmaan/KunstmaanBundlesCMS/issues/1683

### CODE REVIEW

**Comment by delboy1978uk** [comment]
If anyone instantiates this manually though, would that not create a BC break? I realise autowiring will handle it, but are we sure we always get that the magic Symfony way? Other people using bundles might have said `$x = new UrlHelper($etc, $etc, $oopsBrokeIt, $etc);`

**Comment by deZinc** [comment]
@delboy1978uk Yup, that makes it a BC break indeed. So the change has to be added to 5 branch and also added to the upgrade guide.

**Comment by delboy1978uk** [comment]
In it's current state it can be merged into master with no BC break, and insight will stop complaining. 
I can make another ticket and break BC by removing it fully and pull request on 5.0 😀

**Comment by deZinc** [comment]
Let's keep it clean though. :-p
Either we remove everything, or nothing... I wouldn't be surprised if we merge it like this that insight will complain about an unused param in the configurator.

**Comment by delboy1978uk** [comment]
haha you could be right! ok i'll rebase and push again

**Comment by delboy1978uk** [comment]
rebased to 5.0 😀

**Pull request merged**
