### PR TITLE
[AdminListBundle] Change image button image to icon

### PR DESCRIPTION
**Pull request by aistis-**
Hello, I run into a problem. If I use list with configurator where I add buttons, they are printed different in [edit page](https://sc-cdn.scaleengine.net/i/8adf431260cf2d7b36f92a06809c5f41.png) than in [items list](https://sc-cdn.scaleengine.net/i/c243c8d21fa8f5a2ac8a2be7a1af81ce.png). I want them to [look the same](https://sc-cdn.scaleengine.net/i/6f4b8dc63a8c8c585e379547ecd5aecd.png).

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | yes
| Deprecations? | no

### CODE REVIEW

**Comment by roderik** [comment]
@aistis- is this a breaking change? 

also could you please include the table in your pull requests? It's documented in the contributing file

**Comment by aistis-** [comment]
@roderik I guess it is BC for those who does not use crud table, but uses the buttons with with images

**Comment by roderik** [comment]
@aistis- add a small note to the Upgrade-3.4 file that mentions this for 3.4.1

**Comment by aistis-** [comment]
@roderik I will do it next week :)

**Pull request merged**
